### ISSUE TITLE
www is down

### ISSUE THREAD

**Issue by metrue** [lagonapp/lagon#582] opened 2023-02-14 01:27 UTC
**Describe the bug**
The website [lagon.app](https://lagon.app/) is down because of an exception in JavaScript code.

**To Reproduce**
```
cd www
yarn dev
```
access [127.0.0.1:3000](http://127.0.0.1:3000), you see the exception which is thrown from/during `createGlobe`.

**Expected behavior**
I should be able to access live website of lagon.app and local running of www.

**Screenshots**
![Screenshot 2023-02-14 at 09 19 54](https://user-images.githubusercontent.com/1001246/218614005-20f8939b-cfcc-43ed-84fd-0a2edc4943ed.png)
![Screenshot 2023-02-14 at 09 20 11](https://user-images.githubusercontent.com/1001246/218614013-2b8912ca-3a8b-49f6-8801-6c9d0f1ce867.png)

**Information:**
 - OS:  Darwin DMFD93W41Q 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64
 - Browser: chrome (but it works on safari)
 - Version: latest main branch.

**Comment by QuiiBz** [comment] 2023-02-14 17:06
I'm not having any issues on my side, either accessing lagon.app or running `www` locally:

Arc (Chromium 109) and Safari (16.3) in incognito mode:
![Screenshot 2023-02-14 at 18 04 05](https://user-images.githubusercontent.com/43268759/218806816-37922d37-ad86-4984-8f2b-9201eea9c3b7.png)

Could you try updating your browsers and accessing the website again without any extensions?

**Comment by metrue** [comment] 2023-02-15 14:59
The version of my Chrome is `Version 109.0.5414.119 (Official Build) (arm64)`
and I tried on incognito mode it's still not working. 
<img width="1505" alt="Screenshot 2023-02-15 at 22 55 40" src="https://user-images.githubusercontent.com/1001246/219064142-ff0c22db-619d-41b7-bb44-d982ea453dc7.png">

**Comment by QuiiBz** [comment] 2023-02-15 15:10
I've tried again using different OS (macOS, Linux, Windows), browsers (Safari, Chrome, Arc, Firefox), and laptops (Intel and M1 macs) and I'm still unable to reproduce the issue.

Do you have the same error on Cobe's playground? https://cobe-playground.vercel.app/

If so, I would recommend opening an issue on Cobe's repository: https://github.com/shuding/cobe

**Comment by metrue** [comment] 2023-02-16 05:24
Yes, same error on Cobe's playground. 

just raised this issue on Cobe's repo. https://github.com/shuding/cobe/issues/62

**Comment by QuiiBz** [comment] 2023-02-16 06:41
Thanks, closing this issue since it’s not related to Lagon, but will follow the issue you created on Cobe’s repository to land a fix.

**Closed by QuiiBz** 2023-02-16 06:41 UTC
Labels: bug
